name: Copy Docs to Remote

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  copy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_DWARSHUIS }}

      - name: Add Known Hosts
        run: |
          echo "${{ secrets.SSH_KNOWN_HOSTS_DWARSHUIS }}" >> ~/.ssh/known_hosts

      - name: Install expect
        run: |
          sudo apt-get update
          sudo apt-get install -y expect

      - name: Add SSH Key with Passphrase
        run: |
          /usr/bin/expect <<EOF
          spawn ssh-add -
          expect "Enter passphrase for"
          send "${{ secrets.SSH_PASSPHRASE_DWARSHUIS }}\r"
          interact
          EOF

      - name: Copy /docs to Remote
        run: |
          scp -r ./docs user@dwarshuis.com:/test/spec-up-t-demo-on-documentation-website
        env:
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS_DWARSHUIS }}